---
name: Update dependent repositories
on:
  push:
    branches:
      - main
  workflow_run:
    types:
      - completed
    workflows:
      - 'automerge'
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push' }}
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: |
        ["cmd-exclude-prefixes-k8s",
        "cmd-forwarder-sriov",
        "cmd-registry-k8s",
        "cmd-nse-supplier-k8s",
        "cmd-forwarder-vpp"]
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
